name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Gradlew exists and has executable permission
        run: |
          echo "Checking gradlew permissions"
          ls -l ./gradlew || echo "gradlew not found"
          chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run tests
        run: ./gradlew clean test