name: Test

run-name: ${{ github.actor }} is learning GitHub Actions

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Gradlew exists and has executable permission
        run: |
          ls -l ./gradlew
          chmod +x ./gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - run: ./gradlew clean test